#+title:      Refactoring My Emacs and note-taking system
#+date:       [2026-01-18 nie 15:23]
#+filetags:   :denote:emacs:en:orgmode:
#+identifier: 20260118T152327

* Justification
I have an idea, that this system I have created is too big for me now, and to clunky, so I'm not using it efficiently enough to. Right now I'm using mostly few things:
1. Git auto commit
2. Transient menus
3. Spellchecking and spell correct (adding unknown words to the personal dictionary file is great)
4. denote tag system and
5. denote properties
6. Some org features, but not sure how many (well-being maybe)
7. Note system (journaling and regular notes, essays [mostly because of templates])

What I rarely use:
1. Zettel notes style (fleeting and smart)
2. Philosophers/person note templates
3. Other stuff like shortcuts (C-n s), project (C-n p)

I want to use this tool more in the future, create, link and ingest more knowledge from it. I want read and take notes from PDF and ebooks directly from Emacs, without need of jumping between programs.

** Proposition of change (basic)
Remove all unnecessary code I don't use. Start small, from what I mostly use, like journaling, spellchecking, regular notes and all the things that allow simple note manipulation (C-n j and C-n J, C-n t, C-n bm C-n {r,R}, C-n t). Also left well-being tag as this is something, that can be use in the future. Left soft-wrapping as I have it now and note at the center of the buffer. I like this. Light theme I have is also OK for now. I like Emacs panels with "File, Edit, Options, Buffers [...]" and I like tabs. 
Left Transient menu, but maybe simplify it. Give easy way to access all sub-menus if I forget about some feature and want to use it later.

I start to think that maybe I should change my whole note-taking system. Now all notes are in one folder =~/notes= because of the way, how denote is organising file names. I discovered I have 3 main type of notes:
1. Journaling - my daily notes about my personal life. Very sensitive, private information
2. Regular notes - any knowledge notes I done on any topic I might be interested in a given time. This entitles philosophical (from my university, but also my private), different hobbies like linux, psychology, sociology, astrophysics etc. 
3. Technical/documentation notes
For these three types I think I should have different folders, so I can for example push my technical notes to GitHub maybe. My regular notes can then be used for building kind of knowledge garden or something like that, maybe some of them publish on my personal blog (WordPress, Hugo whatever, look for section "In the future").
I wonder if maybe for a fleeting notes I could use one org file that will work as a basket for such ideas or thoughts that just snap or pop from nowhere, are good, but I don't have time or willpower to processed them now. One file in orgmode format would be a good way to caputre them. Denote file it's not that good for this in my opinion as it is more require manual workflow. 

** In the future
1. Use Agenda for tasks and plans
2. Publish my certain articles in a blog platform I host (Hugo, WordPress, something else)
3. Zotero/bibitext integration. PDF reading and note taking from it etc.
4. Left and right panels showing more of information about edited file and about all files. Linking and back-linking etc.
5. Learn what else I can have that will fit nicely in my workflow and let me do easier more things.

* What I like
** Journaling/note-taking
I like Journaling and note-taking  (C-n j and C-n J, C-n t, C-n bm C-n {r,R}, C-n t) and spellchecking (C-F {m,c,b,a}). How spellchecking correction is working for Polish and English is nice. I like this.

* What I don't like
1. Spellchecking is constantly disabling  from no reason, and I need to on it from time to time. Not sure why.
2. Slowness. It is starting really slow now stopping for long time on ~.org-clocl.save.el~ file. I think I don't need this now, because I don't use Agenda much (my change in the near future)

* To be changed
1. Quotes expansion in org files. It is annoying, when writing in english and all ='= are made double =''=. In org files this must be off, and on ONLY in files like ~.el, .lua, .nix~ etc.
2. Learn basic shortcuts for Emacs itself and for my system for note-taking.
